from loader import db

I18N_CACHE = {
    'uz': {
        'welcome': "Assalomu alaykum {username}!",
        'choose_language': "Iltimos tilni tanlang:",
        'login_required': "❗ Siz tizimga kirmagansiz",
        'main_menu': "Asosiy menyu:",
        'login_confirm': "⚠️ Tasdiqlang: bu sizning login ma'lumotlaringizmi?\n\n{username}:{password}",
        'login_success': "✅ Tizimga kirdingiz!",
        'login_fail': "❌ Username yoki password xato!",
        'login_ask': "Iltimos username va password yuboring, shunday ko‘rinishda:\nusername:password",
        'format_error': "❌ Format xato. username:password shaklida yuboring",
        'cancelled': "❌ Bekor qilindi",
        'account_not_logged': "❗ Siz tizimga kirmagansiz",
        'account_session_expired': "🔐 Sessiya tugagan. Qayta login qiling.",
        'account_info': "👤 Account ma'lumotlari:\n\nUsername: {username}\n💰 Balance: {balance}",
        'logout_success': "🚪 Siz tizimdan chiqdingiz.\n\nQayta kirish uchun Login yoki Register tanlang.",
        'login_btn': "🔐 Login",
        'register_btn': "📝 Ro‘yxatdan o‘tish",
        'account_btn': "🧘‍♂️ Hisob",
        'booking_btn': "🎮 Band qilish",
        'history_btn': "📄 Tarix",
        'web_site_btn': "🚪 Sayt",
        'yes_btn': "✅ Ha",
        'no_btn': "❌ Yo‘q",
        'logout_btn': "🔴 Chiqish",
        'back_btn': "🔙 Orqaga",
        'username_prompt': "👤 Username yuboring:",
        'password_prompt': "🔐 Password kiriting:",
        'password_repeat_prompt': "🔐 Passwordni qayta kiriting:",
        'password_mismatch': "❌ Passwordlar mos emas. Qayta urinib ko‘ring.",
        'confirm_registration': "⚠️ Tasdiqlang:\n\nUsername: {username}",
        'username_taken': "❌ Username band yoki ma’lumot xato!",
        'registered_success': "✅ Ro‘yxatdan o‘tdingiz va tizimga kirdingiz!",
        'token_error': "❌ Token olishda xato!",
        'rooms_btn': "🛋 Xonalar",
        'devices_btn': "🖥 Qurilmalar",
        'book_btn': "🎮 Band qilish",
        'rooms_title': "🛋 Xonalar",
        'devices_title': "🖥 Qurilmalar",
        'device_status_free': "✅ Bo‘sh",
        'device_status_busy': "❌ Band",
        'device_status_pending': "Kutib turibdi active bolishini",
        'zone_back_btn': "🔙 Zonelarga qaytish",
        'no_room_btn': 'Xonalari yoq',
        'active_cfrm_btn':"✅ keldi",
        'missed_cfrm_btn':"❌ kelmadi",
        "booking_enter_time": "⏰ Boshlash vaqtini yuboring.\n\nFormat: HH:MM\nMasalan: 18:30",
        "booking_time_format_error": "❌ Vaqt formati xato.\n\nTo‘g‘ri format: HH:MM\nMasalan: 18:30",
        "booking_time_past_error": "❌ Bu vaqt allaqachon o‘tib ketgan.\n\nHozirgi vaqt: {now}",
        "booking_choose_hours": "⌛ Necha soat o‘ynaysiz?\n\nQuyidan tanlang:",
        'booking_time_format_error':"❌ Vaqt formati noto‘g‘ri.\nHH:MM ko‘rinishida kiriting.",
        'booking_confirm_title':"📋 Booking ma’lumotlari:\n\n🕒 Boshlanish: {start}\n⏱ Davomiyligi: {hours} soat\n\nTasdiqlaysizmi?",
        "booking_error":"❌ Booking amalga oshmadi.\nIltimos, qayta urinib ko‘ring."

    },
    'ru': {
        'welcome': "Привет {username}!",
        'choose_language': "Пожалуйста, выберите язык:",
        'login_required': "❗ Вы не вошли в систему",
        'main_menu': "Главное меню:",
        'login_confirm': "⚠️ Подтвердите: это ваши данные для входа?\n\n{username}:{password}",
        'login_success': "✅ Вы вошли в систему!",
        'login_fail': "❌ Неверный username или пароль!",
        'login_ask': "Пожалуйста, отправьте username и password в таком формате:\nusername:password",
        'format_error': "❌ Неверный формат. username:password",
        'cancelled': "❌ Отменено",
        'account_not_logged': "❗ Вы не вошли в систему",
        'account_session_expired': "🔐 Сессия истекла. Пожалуйста, войдите снова.",
        'account_info': "👤 Данные аккаунта:\n\nUsername: {username}\n💰 Баланс: {balance}",
        'logout_success': "Вы вышли из системы.\n\nДля повторного входа выберите Login или Register.",
        'login_btn': "🔐 Войти",
        'register_btn': "📝 Регистрация",
        'account_btn': "🧘‍♂️ Аккаунт",
        'booking_btn': "🎮 Бронирование",
        'history_btn': "📄 История",
        'web_site_btn': "🚪 Вебсайт",
        'yes_btn': "✅ Да",
        'no_btn': "❌ Нет",
        'logout_btn': "🔴 выйти",
        'back_btn': "🔙 Назад",
        'username_prompt': "👤 Введите username:",
        'password_prompt': "🔐 Введите пароль:",
        'password_repeat_prompt': "🔐 Повторите пароль:",
        'password_mismatch': "❌ Пароли не совпадают. Попробуйте снова.",
        'confirm_registration': "⚠️ Подтвердите:\n\nUsername: {username}",
        'username_taken': "❌ Username занят или данные неверны!",
        'registered_success': "✅ Вы зарегистрировались и вошли в систему!",
        'token_error': "❌ Ошибка при получении токена!",
        'rooms_btn': "🛋 Комнаты",
        'devices_btn': "🖥 Устройства",
        'book_btn': "🎮 Забронировать",
        'rooms_title': "🛋 Комнаты",
        'devices_title': "🖥 Устройства",
        'device_status_free': "✅ Свободно",
        'device_status_busy': "❌ Занято",
        'device_status_pending': "Ожидает начала",
        'zone_back_btn': "🔙 Назад к зонам",
        'no_room_btn': "Нет Комнаты",
        'active_cfrm_btn':"✅ пришоль",
        'missed_cfrm_btn':"❌ не пришоль",
        "booking_enter_time": "⏰ Отправьте время начала.\n\nФормат: HH:MM\nНапример: 18:30",
        "booking_time_format_error": "❌ Неверный формат времени.\n\nПравильный формат: HH:MM\nНапример: 18:30",
        "booking_time_past_error": "❌ Это время уже прошло.\n\nТекущее время: {now}",
        "booking_choose_hours": "⌛ Сколько часов будете играть?\n\nВыберите ниже:",
        'booking_time_format_error':"❌ Неверный формат времени.\nВведите в формате HH:MM.",
        'booking_confirm_title':'📋 Данные бронирования:\n\n🕒 Начало: {start}\n⏱ Длительность: {hours} часов\n\nПодтвердить?',
        "booking_error":"❌ Не удалось создать бронирование.\nПопробуйте ещё раз."
    },
    'en': {
        'welcome': "Hello {username}!",
        'choose_language': "Please select your language:",
        'login_required': "❗ You are not logged in",
        'main_menu': "Main menu:",
        'login_confirm': "⚠️ Confirm: are these your login credentials?\n\n{username}:{password}",
        'login_success': "✅ You are logged in!",
        'login_fail': "❌ Wrong username or password!",
        'login_ask': "Please send username and password in this format:\nusername:password",
        'format_error': "❌ Wrong format. username:password",
        'cancelled': "❌ Cancelled",
        'account_not_logged': "❗ You are not logged in",
        'account_session_expired': "🔐 Session expired. Please login again.",
        'account_info': "👤 Account info:\n\nUsername: {username}\n💰 Balance: {balance}",
        'logout_success': "🚪 You have logged out.\n\nSelect Login or Register to log in again.",
        'login_btn': "🔐 Login",
        'register_btn': "📝 Register",
        'account_btn': "🧘‍♂️ Account",
        'booking_btn': "🎮 Booking",
        'history_btn': "📄 History",
        'web_site_btn': "🚪 Web Site",
        'yes_btn': "✅ Yes",
        'no_btn': "❌ No",
        'logout_btn': "🔴 logout",
        'back_btn': "🔙 Back",
        'username_prompt': "👤 Send your username:",
        'password_prompt': "🔐 Enter password:",
        'password_repeat_prompt': "🔐 Repeat password:",
        'password_mismatch': "❌ Passwords do not match. Try again.",
        'confirm_registration': "⚠️ Confirm:\n\nUsername: {username}",
        'username_taken': "❌ Username taken or invalid data!",
        'registered_success': "✅ You have registered and logged in!",
        'token_error': "❌ Error while getting token!",
        'rooms_btn': "🛋 Rooms",
        'devices_btn': "🖥 Devices",
        'book_btn': "🎮 Book",
        'rooms_title': "🛋 Rooms",
        'devices_title': "🖥 Devices",
        'device_status_free': "✅ Available",
        'device_status_busy': "❌ Busy",
        'device_status_pending': "It's waiting for",
        'zone_back_btn': "🔙 Back to zones",
        'no_room_btn': "there is not rooms",
        'active_cfrm_btn':"✅ Active",
        'missed_cfrm_btn':"❌ missed",
        "booking_enter_time": "⏰ Send the start time.\n\nFormat: HH:MM\nExample: 18:30",
        "booking_time_format_error": "❌ Invalid time format.\n\nCorrect format: HH:MM\nExample: 18:30",
        "booking_time_past_error": "❌ This time has already passed.\n\nCurrent time: {now}",
        "booking_choose_hours": "⌛ How many hours will you play?\n\nChoose below:",
        "booking_time_format_error":"❌ Invalid time format. \nUse HH:MM format.",
        'booking_confirm_title':"📋 Booking details:\n\n🕒 Start: {start}]\n⏱ Duration: {hours} hours\n\nConfirm?",
        'booking_error': "❌ Booking failed.\nPlease try again."
    }
}



async def t(telegram_id: int, key: str, **kwargs):
    lang = await db.get_language(telegram_id=telegram_id)
    if not lang:
        lang = 'uz'

    text = I18N_CACHE.get(lang, I18N_CACHE['uz']).get(key, key)
    return text.format(**kwargs)